Update secret.yml

diff --git a/.github/workflows/secret.yml b/.github/workflows/secret.yml
--- a/.github/workflows/secret.yml
+++ b/.github/workflows/secret.yml
@@ -10,18 +10,17 @@ jobs:
   build:
     runs-on: ubuntu-latest
     steps:
-      - name: Check PR title
-              env:
-                TITLE: ${{ secret.GITHUB }}
-              run: |
-                 if [[ "$TITLE" =~ ^crnic ]]; then
-                 echo "Token Valido"
-                 exit 0
-                 else
-                 echo "Token INvalido"
-                 exit 1
-                 fi
-    
-      - uses: actions/checkout@v3
-      - name: Run a one-line script
-        run: echo Hello, world!
+    - name: Validar secret
+      env:
+          TITLE: ${{ secret.GITHUB }}
+      run: |
+        if [[ "$TITLE" =~ ^crnic ]]; then
+        echo "Token Valido"
+        exit 0
+        else
+        echo "Token INvalido"
+        exit 1
+        fi
+          
+    - name: Imprimir mensaje desde reusable-lab.yml
+      run: echo "Este es un mensaje desde el flujo de trabajo reusable-lab.yml"
